{{ $name := .Release.Name }}
{{ $namespace := .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: "pre-install"
    helm.sh/hook-weight: "2"
  name: {{ $name }}-rolebinding
  namespace: {{ $namespace }}
  labels:
    {{- include "slurm-cluster.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: {{ $name }}-role
  apiGroup: rbac.authorization.k8s.io