{{ if .Values.persistence.csi.subDir }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-delete-job
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: "post-delete"
  labels:
    app.kubernetes.io/name: {{ include "lustre-csi-pv.name" . }}
    helm.sh/chart: {{ include "lustre-csi-pv.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      nodeName: hqcomp01
      securityContext:
        {{- if .Values.securityContext.runAsUser }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        {{- end }}
        {{- if .Values.securityContext.runAsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
        {{- end }}
        {{- if .Values.securityContext.fsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
        {{- end }}
      containers:
      - image: 172.236.5.21:31500/etc/busybox:1.0.0
        name: create-dir
        command:
        - /bin/sh
        - -c
        args:  
        - "rm -rf /mnt/lustre/{{ .Values.persistence.name }}"
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-lustre
            mountPath: /mnt/lustre
      volumes:
        - name: host-lustre
          hostPath:
            path: {{ .Values.persistence.csi.rootDir | default "/mnt/lustre/k8s-lustre-csi" }}
            type: Directory
      restartPolicy: Never
  backoffLimit: 5
{{ end }}